### PR TITLE
fixed colorizing, added glow variants

### PR DESCRIPTION
**Pull request by Nordall**

### CODE REVIEW

**Comment by adrido** [comment]
Thanks, Ill do a few tests, and then merge it.

**Comment by adrido** [comment]
Did you forgot to add the texture or is the minetest.inventorycube not necessarry?
```
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_round.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
ERROR[Main]: generateImage(): Could not load image "darkage_glow_glass_square.png" while building texture; Creating a dummy image
```

**Comment by Nordall** [comment]
In contrast to what I said in my email, with the two added commits everything should be fixed now.

**Comment by adrido** [comment]
Just fixed a craft reciepe name. 

Thanks for your work.

**Pull request merged**
